/*============================================================================== 
 * Copyright (c) 2012-2014 Qualcomm Connected Experiences, Inc. All Rights Reserved. 
 * ==============================================================================*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Vuforia;

/// <summary>
/// UI Event Handler class that handles events generated by user-tap actions
/// over the UI Options Menu
/// </summary>
public class SmartTerrainUIEventHandler : ISampleAppUIEventHandler { 
    
    #region PUBLIC_MEMBER_VARIABLES
    public override event System.Action CloseView;
    public override event System.Action GoToAboutPage;
    #endregion PUBLIC_MEMBER_VARIABLES
    
    #region PRIVATE_MEMBER_VARIABLES
    private static bool sExtendedTrackingIsEnabled;
    private SmartTerrainUIView mView;
    private SmartTerrainTracker mTracker;
    private ReconstructionBehaviour mReconstructionBehaviour;
    #endregion PRIVATE_MEMBER_VARIABLES
   
	#region PUBLIC_MEMBER_PROPERTIES
    public SmartTerrainUIView View
    {
        get {
            if(mView == null){
                mView = new SmartTerrainUIView();
                mView.LoadView();
            }
            return mView;
        }
    }

    #endregion PUBLIC_MEMBER_PROPERTIES
    
    #region PUBLIC_METHODS
    public override void UpdateView (bool tf)
    {
        this.View.UpdateUI(tf);
    }
    
    public override  void Bind()
    {
        this.View.mCloseButton.TappedOn         += OnTappedToClose;
        this.View.mAboutLabel.TappedOn          += OnTappedOnAboutButton;
		this.View.mStartStopScanning.TappedOn += OnTappedOnScanning;
		this.View.mReset.TappedOn += OnTappedOnReset;

        // register Vuforia started callback
        VuforiaAbstractBehaviour vuforiaBehaviour = (VuforiaAbstractBehaviour)FindObjectOfType(typeof(VuforiaAbstractBehaviour));
        if (vuforiaBehaviour)
        {
            vuforiaBehaviour.RegisterVuforiaStartedCallback(EnableContinuousAutoFocus);
            vuforiaBehaviour.RegisterOnPauseCallback(OnPause);
        }

        mTracker = TrackerManager.Instance.GetTracker<SmartTerrainTracker>();
        mReconstructionBehaviour = (ReconstructionBehaviour)FindObjectOfType(typeof(ReconstructionBehaviour));
        if (!mReconstructionBehaviour)
            Debug.LogError("No ReconstructionBehaviour found in scene!");
    }
    
    public override  void UnBind()
    { 
        this.View.mCloseButton.TappedOn         -= OnTappedToClose;
        this.View.mAboutLabel.TappedOn          -= OnTappedOnAboutButton;
		this.View.mStartStopScanning.TappedOn   -= OnTappedOnScanning;
		this.View.mReset.TappedOn               -= OnTappedOnReset;

        // unregister Vuforia started callback
        VuforiaAbstractBehaviour vuforiaBehaviour = (VuforiaAbstractBehaviour)FindObjectOfType(typeof(VuforiaAbstractBehaviour));
        if (vuforiaBehaviour)
        {
            vuforiaBehaviour.UnregisterVuforiaStartedCallback(EnableContinuousAutoFocus);
            vuforiaBehaviour.UnregisterOnPauseCallback(OnPause);
        }

        this.View.UnLoadView();
        mView = null;
    }
    
     public override  void TriggerAutoFocus()
    {
        StartCoroutine(TriggerAutoFocusAndEnableContinuousFocusIfSet());
    }
   
    #endregion PUBLIC_METHODS
    
    #region PRIVATE_METHODS
  
	 /// <summary>
    /// Activating trigger autofocus mode unsets continuous focus mode (if was previously enabled from the UI Options Menu)
    /// So, we wait for a second and turn continuous focus back on (if options menu shows as enabled)
    /// </returns>
    private IEnumerator TriggerAutoFocusAndEnableContinuousFocusIfSet()
    {
        //triggers a single autofocus operation 
        if (CameraDevice.Instance.SetFocusMode(CameraDevice.FocusMode.FOCUS_MODE_TRIGGERAUTO)) {
              this.View.FocusMode = CameraDevice.FocusMode.FOCUS_MODE_TRIGGERAUTO;
        }
        
        yield return new WaitForSeconds(1.0f);
         
        //continuous focus mode is turned back on 
        if (CameraDevice.Instance.SetFocusMode(CameraDevice.FocusMode.FOCUS_MODE_CONTINUOUSAUTO)) {
          this.View.FocusMode = CameraDevice.FocusMode.FOCUS_MODE_CONTINUOUSAUTO;
        }
        
        Debug.Log (this.View.FocusMode);
        
    }

    private void OnPause(bool pause)
    {
        if (!pause)
        {
            // set to continous autofocus
            CameraDevice.Instance.SetFocusMode(CameraDevice.FocusMode.FOCUS_MODE_CONTINUOUSAUTO);
        }
    }

    //We want autofocus to be enabled when the app starts
    private void EnableContinuousAutoFocus()
    {
        if (CameraDevice.Instance.SetFocusMode(CameraDevice.FocusMode.FOCUS_MODE_CONTINUOUSAUTO))
        {
            this.View.FocusMode = CameraDevice.FocusMode.FOCUS_MODE_CONTINUOUSAUTO;
        }
    }
	

	  
    private void OnTappedToClose()
    {
        if(this.CloseView != null)
        {
            this.CloseView();
        }
    }
    
    
    private void OnTappedOnAboutButton(bool tf)
    {
        if(this.GoToAboutPage != null)
        {
            this.GoToAboutPage();
        }
    }
	
	private void OnTappedOnScanning(bool tf)
	{
	    if ((mReconstructionBehaviour != null) && (mReconstructionBehaviour.Reconstruction != null))
	    {
	        if (this.View.mStartStopScanning.Title == "Start")
	        {
	            Debug.Log("Start Scanning [" + Time.time + "]");
                mReconstructionBehaviour.Reconstruction.Start();
	            this.View.mStartStopScanning.Title = "Stop";
	        }
	        else
	        {
	            Debug.Log("Stop Scanning [" + Time.time + "]");
                mReconstructionBehaviour.Reconstruction.Stop();
	            this.View.mStartStopScanning.Title = "Start";
	        }
	    }

	    OnTappedToClose();
	}
		
	private void OnTappedOnReset(bool tf)
	{
	    if ((mReconstructionBehaviour != null) && (mReconstructionBehaviour.Reconstruction != null))
	    {
	        Debug.Log("Reset Smart Terrain [" + Time.time + "]");

	        bool trackerWasActive = mTracker.IsActive;
	        // first stop the tracker
	        if (trackerWasActive)
	            mTracker.Stop();
	        // now you can reset...
            mReconstructionBehaviour.Reconstruction.Reset();
	        // ... and restart the tracker
	        if (trackerWasActive)
	        {
	            mTracker.Start();
                mReconstructionBehaviour.Reconstruction.Start();
	        }

	        this.View.mStartStopScanning.Title = "Stop";
	    }
	    OnTappedToClose();
	}
	
   
    #endregion PRIVATE_METHODS
}

